### ISSUE TITLE
Support for opaque/private types

### ISSUE THREAD

**Issue by gornik** [ejpcmac/typed_struct#10]
Hi @ejpcmac,

Thank you for typed_struct, I've been playing with it and it's really nice. I think it would be great if apart from generating a `@type`, it could support generating a `@typep` or an `@opaque` definition as well (private would probably be not that useful, but support for opaque types would be nice). This could be specified as an option, e.g. like this:

```elixir
defmodule MyStruct do
  use TypedStruct

  typedstruct as: :opaque do
    field :name, String.t()
  end
end
```
where `as` would allow: `:type` (default), `:typep`, `:opaque`.

Let me know what you think, I was looking at the code and I think I could take a stab at this.

**Comment by ejpcmac** [comment]
Hi @gornik,

This is indeed a feature which has its place in `typed_struct`. Please do it if you have some time available—I don’t have any this week-end—, I’ll merge this happily :)

As for the API, I don’t see any use case for a private type for the struct, as the struct if effectively usable from outside the module. What do you think of this instead:

```elixir
defmodule MyStruct do
  use TypedStruct

  typedstruct opaque: true do
    field :name, String.t()
  end
end
```

Let me know.

**Comment by gornik** [comment]
You're right, private types wouldn't make much sense and `opaque: true` is much better. I'll try to add it then, thank you!
