### ISSUE TITLE
A field with a default value set to nil should not be enforced

### ISSUE THREAD

**Issue by lasseebert** [ejpcmac/typed_struct#14]
When the struct has `enforce: true`, one can override this by setting a default value on a field. Something like this:

```
typedstruct enforce: true do
  field :non_enforced_field, integer, default: 42
end
```

But it is not possible to default to nil (it will not un-enforce the field:

```
typedstruct enforce: true do
  # This will not work. The field is still enforced
  field :non_enforced_field, integer | nil, default: nil
end
```

I know that adding `enforce: false` on the field will do the same thing, since `nil` is the default value for non-enforces fields, but for the explicitness and readability, it would be nice the set the default value to `nil`.

If you agree, @ejpcmac, I will be happy to give it a shot.

**Comment by ejpcmac** [comment]
Hello @lasseebert,

An enforced value must be non-nil. By setting `enforce: true` globally, you *mean* that `:non_enforced_field` is in fact enforced. The way you define it says the same thing as doing:

```elixir
defmodule Test do
  @enforce_keys [:non_enforced_field]
  defstruct non_enforced_field: nil

  @type t() :: %__MODULE__{non_enforced_field: integer() | nil}
end
```

Which is obviously invalid: you cannot create a `%Test{}` with `:non_enforced_field` set to nil.

In your first example, the `enforce: true` is not overriden: the field is still enforced, but since it has a default value, your user do not need to provide a non-nil value.

**Comment by lasseebert** [comment]
@ejpcmac 

Thanks for the explanation :)
I thought setting a default value would unset the global `enforce: true` for that field (ref [the docs](https://github.com/ejpcmac/typed_struct#general-usage)):

> A key with a default value is not enforced.

which is why I expected 

```elixir
typedstruct enforce: true do
  field :non_enforced_field, integer | nil, default: nil
end
```

to generate something like

```elixir
defmodule Test do
  @enforce_keys []
  defstruct non_enforced_field: nil

  @type t() :: %__MODULE__{non_enforced_field: integer() | nil}
end
```

**Comment by ejpcmac** [comment]
> I thought setting a default value would unset the global `enforce: true` for that field (ref [the docs](https://github.com/ejpcmac/typed_struct#general-usage)):
> 
> > A key with a default value is not enforced.

Mmm. Maybe that’s a documentation issue then. I’ll fix it in the next release.

**Comment by lasseebert** [comment]
Thanks for your quick responses. It all makes sense :)
I will consider this issue closed, but I will let you close it in case you want to leave it open for the doc changes.

**Comment by ejpcmac** [comment]
@lasseebert You’re welcome. Please let it open so I can remember it.

**Comment by ejpcmac** [comment]
Mmm. In fact that’s a bug. Reading my tests, I have :

```elixir
test "does not enforce keys for fields with a default value" do
  refute :with_default in EnforcedTypedStruct.enforce_keys()
end

test "does not enforce keys for fields with a default value set to `false`" do
  refute :with_false_default in EnforcedTypedStruct.enforce_keys()
end
```

So I’ll add a test for the default value set to `nil`. That’s a corner case. Property testing would have catch it, but I haven’t got the time to figure how to property-test code generation.

**Comment by lasseebert** [comment]
Awesome 👍 🙂
