### ISSUE TITLE
Non-clashing module attributes

### ISSUE THREAD

**Issue by lasseebert** [ejpcmac/typed_struct#15]
I just got hit by the auto generated module attributes (`@fields`, `@types` and `@keys_to_enforce`).

I was changing an existing `defstruct` to use TypedStruct, but I already had a module attribute called `@types`. It took me a while to figure out what went wrong :)

ExUnit and Ecto both [solves](https://github.com/elixir-lang/elixir/blob/d1559660740c85d94e3cff942ff0b6c8f7d31818/lib/ex_unit/lib/ex_unit/case.ex#L515) [this](https://github.com/elixir-ecto/ecto/blob/78778600e9d5e249a9fccb76246a63cafa2e656f/lib/ecto/schema.ex#L430-L439) by prepending the library name to the module attributes.

Perhaps typed_struct could do the same?

I'd be happy to do a PR.

**Comment by ejpcmac** [comment]
I’m working on #14 right now, I’ll solve this one right after.

**Comment by ejpcmac** [comment]
Thank you for your reports by the way!

**Comment by lasseebert** [comment]
Awesome. Thanks for the quick response and fix 😊
